DmesonAnalysers/DmesonAnalysis

- utils/AnalysisUtils.py
Ciao @fcatalan92, these methods could be useful for the working-point optmisation script that we should develop
> Add utils functions for computation of prompt (feed-down) fraction with fc and Nb theory-driven methods

- ComputeCutVarPromptFrac.py
- configfiles/datadrivenfprompt/config_Dplus_PromptFrac_pp5TeV.yml
- utils/AnalysisUtils.py
- utils/StyleFormatter.py
Add possibility to compare data-driven prompt (non-prompt) fraction with estimates with theory-driven methods
> Add comparison to theory-driven methods

- ComputeCutVarPromptFrac.py
- configfiles/datadrivenfprompt/config_Dplus_PromptFrac_pp5TeV.yml
- utils/AnalysisUtils.py
- Add possibility to set correlation among sets of cuts (either fully correlated or uncorrelated)
- Add return of chi2/ndf from minimisation procedure
> Add covariances among different sets of cuts and return of chi2/ndf

- ML/TrainTestMultiClass.py
- ML/config_Training_Dplus.yml
- ML/config_Training_Ds.yml
- Reorganization of the script
- Add the possibility to perform only training or application (loading saved models)
> Developments of the ML script

- ComputeDataDrivenCrossSection.py
- runanalysistask/RunAnalysisDplusDsTask.cc
- runanalysistask/runAnalysis_config_LHC19h1a2_1.yml
- utils/AnalysisUtils.py
- utils/StyleFormatter.py
- Add script for D-meson cross section computation with data-driven prompt (feed-down) fraction
- Minor fixes to util methods and runanalysis script
>  Add script for cross section computation + minor fixes

- ML/TrainTestMultiClass.py
- It allows to use a list of files in input
- in the future could be used to load root files adding in the config the name of the tree (if necessary)
> Use method to load input files from utils

- ML/TrainTestMultiClass.py
- ML/config_Training_Dplus.yml
- ML/config_Training_Ds.yml
- add output file with hyper-parameters optimisation output
- add arguments for hyper-parameters optimisation in yaml config file
- move dictionary of hyper-parameters in list of dictionaries (one for each pT bin)
> Apply minor modifications in hyper-parameters optimisation

- CombineAccTimesEff.py
- CompareCrossSecToFONLL.py
- ComputeEfficiencyDplusDs.py
- GetRawYieldsDplusDs.py
- Produce pdf files also in batch mode
-  Add script to compare cross section with FONLL
> Add script to compare cross section with FONLL and fix batch mode

- ProjectDplusDsSparse.py
- configfiles/config_Ds_pp_MC_tree.yml
- optimisation/ScanSelectionsTree.py
- optimisation/config_Dplus_pp5TeV_Optimisation.yml
- optimisation/config_Ds_pp5TeV_Optimisation.yml
In particular, avoiding the conversion to `list` in `fill_hist` save ~10-15% of the scan time
> Various minor fixes to significance opt. + add Ds configuration

- optimisation/ScanSelectionsTree.py
RaaSpline was not defined in case Raa was a number in the config file
> Minor fix in RaaSpline definition

- utils/AnalysisUtils.py
Minor fix: rearranged parameters in funcSignal definition
> Minor fix in GetExpectedBkgFromMC method

- optimisation/ScanSelectionsTree.py
- optimisation/config_Ds_MC_Optimisation_ITS3.yml
- utils/AnalysisUtils.py
- ScanSelectionTree.py: loop over a pramater from df/TTree is now possible without double the code  
- config_Ds_MC_Optimisation_ITS3.yml: add a flag in order to evaluate expected signal from Prompt or FD and a flag for df parameter cuts
- AnalysisUtils.py: add protection in case effPrompt/effFD is 0
> Add loop over df/TTree parameter in ScanSelectionsTree

- ComputeDataDrivenCrossSection.py
- RunFullAnalysis.sh
> Adapt RunAnalysis script to run for data-driven analyses and D+

- comparisons/CompareGraphs.py
- comparisons/config_comparison.yml
- utils/AnalysisUtils.py
- bins can be differen but compatible (i.e. ```[2-3-4-5-6]``` and ```[2-4-6]```)
> Add function to compute ratios among histos with different bins

- ComputeCutVarPromptFrac.py
- ProjectSignifNtuple.py
- configfiles/datadrivenfprompt/config_Ds_FDFrac_MC_ITS2.yml
- optimisation/ScanSelectionsTree.py
- utils/AnalysisUtils.py
- Raa from model available in ComputeCutVarPromptFrac.py
- Error evaluation for Signal, EffAccPrompt/FD in ScanSelectionsTree.py
- Add error bar in Signal, EffAccPrompt/FD projection and minor modification in selections to apply list definition in ProjectSignifNtuple.py
- config-file for ComputeCutVarPromptFrac.py
> Raa from model and Error evaluation 

- ComputeCutVarPromptFrac.py
- configfiles/datadrivenfprompt/config_Ds_FDFrac_MC_ITS2.yml
- optimisation/ScanSelectionsTree.py
- ComputeCutVar: add raw yields Poisson smearing possibility
- ScanSelectionsTree: efficiency times acc error fixed
> Smearing and ScanSelectionsTree Efficiency fixing 

- ComputeCutVarPromptFrac.py
- ComputeEfficiencyDplusDs.py
- comparisons/CompareEfficiencies.py
- comparisons/CompareGraphs.py
- systematics/correlation/CheckCorrAmongVariations.py
- systematics/correlation/config_corr.yml
- systematics/genptshape/GetPtWeightSyst.py
- add script to evaluate correlation among different sources of systematic uncertainties
- add various minor improvements (on graphic style and code)
> Add script for correlation between syst. unc. + minor improvements

- merge/MergeTrainOutputs.py
- utils/AnalysisUtils.py
Improvements in script for manual merging:
- move to the usage of ```alien.py``` to speed up download
- separate download from merging (if download interrupted, it restarts from the point where it was interrupted)
> Improve script for manual merging + minor fix

- GetRawYieldsDplusDs.C
- GetRawYieldsDplusDs.py
- comparisons/CompareGraphs.py
- comparisons/config_comparison.yml
- filterdata/FilterTree4ML.py
- filterdata/config_Dplus_MC_skim_pp5TeV.yml
- filterdata/config_Dplus_data_skim_pp5TeV.yml
- filterdata/config_Ds_MC_skim_pp5TeV.yml
- filterdata/config_Ds_data_skim_pp5TeV.yml
- utils/DfUtils.py
New features added:
- higher degree polynomials for background mass fit functions
- missing values for training
- comparison of uncertainties in compare script
> Add few new features

- ML/MLClassification.py
- ML/TrainTestMultiClass.py
- ML/config_Application_Dplus_mult.yml
- ML/config_Application_Ds_mult.yml
- ML/config_Training_Dplus_mult.yml
- ML/config_Training_Ds_ITS3_mult.yml
- ML/config_Training_Ds_binary.yml
- ML/config_Training_Ds_mult.yml
- README.md
To perform the binary classification, the FD file in the configuration must be set to null and the label lists must have only two entries.
Fix #109
> Update to latest hipe4ml and add binary case

- systematics/rawyields/RawYieldSystematics.cc
- systematics/rawyields/config_multi_trial_DplusPrompt_pp.yml
- systematics/rawyields/config_multi_trial_DsFD_pp.yml
- systematics/rawyields/config_multi_trial_Ds_PbPb.yml
- Add possibility to run the multi-trial only for selected pT bins
- Add configurations for peak mean fixed to central value +/- uncertainty 
- Add config file for prompt D+ in pp@5 TeV
> Minor improvements in script for raw-yield systematic uncertainty

- ComputeVisibleCrossSection.py
- comparisons/CompareCrossSecToFONLL.py
- utils/AnalysisUtils.py
- split uncertainties in pT-integrated cross sections
- add possibility to account only for the numerator uncertainty in graph ratios
> Minor modifications

- models/CookFONLLPythiaPred.C
Add predictions needed for non-prompt D paper:
- cross sections of non-prmopt D from B, B_s and Lambda_b
- used BR and FF
> Add in output file single Hb contributions and used BR and FF

- ComputeCutVarPromptFrac.py
- optimisation/ScanSelectionsTree.py
- optimisation/config_Dplus_pp5TeV_Optimisation.yml
- optimisation/config_Ds_MC_Optimisation_ITS3.yml
- optimisation/config_Ds_pp5TeV_Optimisation.yml
@stefanopolitano I just fixed a missing part, i.e. the opening of the file containing the bkg correction factor https://github.com/DmesonAnalysers/DmesonAnalysis/blob/b39b7c34f3ff158ebe942e9549649fa65543f20a/optimisation/ScanSelectionsTree.py#L330 and some pylint warnings
> Fix bkg correction factor + pylint

- comparisons/CompareGraphs.py
Hi! I changed the config. files, but I forgot to commit the changes to CompareGraphs
> Add minor changes to CompareGraphs.py

- ProjectDplusDsSparse.py
- configfiles/config_Ds_PbPb_MC_010.yml
- configfiles/config_Ds_PbPb_MC_010_highpt.yml
- configfiles/config_Ds_PbPb_MC_3050.yml
- configfiles/config_Ds_PbPb_MC_3050_highpt.yml
- configfiles/config_Ds_pp_MC_tree.yml
- utils/TaskFileLoader.py
> Fixes for sparse projection

- filterdata/FilterTree4ML.cc
- filterdata/FilterTree4ML.py
- filterdata/config_Dplus_MC_skim_pp5TeV.yml
- filterdata/config_Dplus_data_skim_pp5TeV.yml
- filterdata/config_Ds_MC_skim_PbPb5TeV.yml
- filterdata/config_Ds_MC_skim_pp5TeV.yml
- filterdata/config_Ds_data_skim_PbPb5TeV.yml
- filterdata/config_Ds_data_skim_pp5TeV.yml
- filterdata/config_LctopK0s_MC_skim_pp5TeV.yml
- filterdata/config_LctopK0s_data_skim_pp5TeV.yml
Implement different bit selections to have correct output datasets for each decay channel (D+, Ds, Lc->pKpi, Lc->pK0s, Lc->piL)
> Adapt filter scripts to work with specific channel bits

- ML/MLApplication.py
- ML/MLClassification.py
- ML/config_Application_Dplus_mult.yml
- ML/config_Application_Dplus_mult_lowpT.yml
- ML/config_Application_Ds_mult.yml
- ML/config_Training_Dplus_mult.yml
- ML/config_Training_Dplus_mult_lowpT.yml
- ML/config_Training_Ds_ITS3_mult.yml
- ML/config_Training_Ds_PbPb010.yml
- ML/config_Training_Ds_PbPb3050.yml
- ML/config_Training_Ds_binary.yml
- ML/config_Training_Ds_mult.yml
- ML/config_Training_LctopK0s_13TeV.yml
- ML/config_Training_LctopK0s_5TeV.yml
- models/ModifyFONLLForPromptLc.py
@fcatalan92 @stefanopolitano @danielbattistini I slightly changed the ML config file in order to avoid possible mistakes due to the wrong order of labels in the lists, please have a look if it is fine for you
> Improve ML yaml config + possibility to modify FONLL for Lc using .txt files

- optimisation/ScanSelectionsTree.py
> Fix bkg sampling

- ComputeCutVarPromptFrac.py
- ComputeDataDrivenCrossSection.py
- ComputeDataDrivenFraction.py
- ComputeEfficiencyDplusDs.py
- configfiles/datadrivenfprompt/config_Dplus_PromptFrac_pp5TeV.yml
- configfiles/datadrivenfprompt/config_Ds_FDFrac_MC_ITS2.yml
- configfiles/datadrivenfprompt/config_Ds_PromptFrac_pp5TeV.yml
- utils/AnalysisUtils.py
@stefanopolitano could you please have a look at the changes in ComputeCutVarPromptFrac.py? As it was before, the background was mandatory even if no smearing is applied, so I think it was a modification that you applied for the ITS3 studies. Thanks!
> Improvements for data-driven fraction estimation

- GetRawYieldsDplusDs.C
- femto/GetPurityVsKstar.py
- femto/ProjectMassFromFemtoTask.py
- femto/config_purity_estimate_pp13TeV_HM.yml
- runanalysistask/RunAnalysisDplusDsLcTask.cc
- utils/AnalysisUtils.py
> Implement improvements for femto + add options for Bayesian PID variables in tree

- ProjectDplusDsTree.py
- models/compare_fonll_pred.py
- models/cook_fonll_nonprompt_ds.py
- models/pythia8sim/GetNonPrompDPredictionFromPythia.py
- optimisation/ScanSelectionsTree.py
- requirements.txt
- runanalysistask/ValidateTreeCreator.py
- systematics/checks/CheckEffVar.py
- systematics/checks/CheckMassShaping.py
- systematics/tracking/PropagateTrackSystToD.py
- utils/AnalysisUtils.py
- utils/DfUtils.py
Pls have a look if everything seems fine
> Remove dependence from root_numpy

- ML/MLClassification.py
- ProjectDplusDsSparse.py
- ProjectDplusDsTree.py
- filterdata/FilterTree4ML.py
- models/ModifyFONLLForPromptLc.py
- models/pythia8sim/GetNonPrompDPredictionFromPythia.py
- requirements.txt
- runanalysistask/ValidateTreeCreator.py
- systematics/fraction/ComputeTheoryDrivenFpromptMultSyst.py
- utils/AnalysisUtils.py
- utils/DfUtils.py
> Move to uproot4

- ProjectDplusDsSparse.py
This feature might be useful, since the efficiencies are not exactly the same apparently (the one for Ds from Bs is lower)
> Add possibility to select only a b-hadron species for FD efficiencies

- utils/TaskFileLoader.py
> Add protection for inputs without reco sparses

- resonances/ComputeResoDauEff.py
- resonances/config_proj_reso.yml
This PR contains:
- Script to compute selection efficiency for resonance daughters (ComputeResoDauEff.py)
- Minor update in resonance config file
> Resonance daughters efficiency estimation

- resonances/config_proj_reso.yml
- resonances/extract_rawyield_DV0reso.py
It requires https://github.com/flarefly/flarefly/pull/58
> Improve evaluation of S and B and Ds1+ selections in HM

- resonances/propagate_frac.py
Improvements:
- load hypothesis factors from file (based on Ds/D nonprompt/prompt double ratios)
- apply multiplication factor to corr yield of nonprompt instead of fraction directly
> Improve non-prompt fraction propagation from D to D resonance

- resonances/ComputeResoDauEff.py
- resonances/compute_integrated_recoeff.py
- resonances/compute_reso_crosssec.py
- resonances/config_proj_reso.yml
This PR contains:
- resonances/ComputeResoDauEff.py: updates to script producing 3D efficiency maps
- resonances/compute_integrated_recoeff.py: script to compute pt-integrated resonance efficiency (to be merged to existing script for resonance efficiency estimation)
- resonances/compute_reso_crosssec.py: script to compute pt-integrated resonance yields and cross sections
- resonances/config_proj_reso.yml: small modification to configuration file to include multiplicity weights
> Efficiency map, pt-integrated efficiency and pt-integrated yields scripts

- run3/flow/flow_analysis_utils.py
- run3/flow/get_vn_vs_mass.py
- run3/flow/project_thnsparse.py
- run3/flow/run_full_flow_analysis.py
This PR adds the possibility to estimate the `vn` of D mesons in Run 3 with the `delta_phi` method. In addition, the code was cleaned and comments were added
> Implementing DeltaPhi method for vn estimation in Run3 + code cleaning

- run3/flow/README_FLOW.md
- run3/flow/compute_reso.py
- run3/flow/flow_analysis_utils.py
- run3/flow/get_vn_vs_mass.py
- run3/flow/project_thnsparse.py
- run3/flow/run_full_flow_analysis.py
This PR cleans the code for flow analyses in Run 3 and adds the correct uncertainty propagation for the vn uncertainty estimated with the ep method
> Cleaning flow analyses code + adding vn_ep uncertainty estimation

- run3/flow/flow_analysis_utils.py
- run3/flow/get_vn_vs_mass.py
- run3/flow/project_thnsparse.py
This PR fixes the resolution computation in thnsparse projection and adjusts the style of inv. mass plots
> Vn resolution computation

- run3/flow/flow_analysis_utils.py
set the directory of each `histo` to `0` and fix `infile_path` in `getListOfHisots`
> Fixed some issues in flow_analysis_utils.py

- run3/flow/systematics/README_MULTITRIAL.md
- run3/flow/systematics/compute_syst_multitrial.py
- run3/flow/systematics/make_yaml_for_syst.py
- run3/flow/systematics/modifications_config.yml
- run3/flow/systematics/multitrial.sh
This PR adds the scripts for computing the fit systematic in flow analyses
> Adding scripts for flow multitrial systematisc

- run3/flow/flow_analysis_utils.py
- run3/flow/get_vn_vs_mass.py
- run3/flow/invmassfitter/InvMassFitter.cxx
- run3/flow/invmassfitter/InvMassFitter.h
- run3/flow/invmassfitter/VnVsMassFitter.cxx
- run3/flow/invmassfitter/VnVsMassFitter.h
- utils/FitUtils.py
Moving the classes `AliHFInvMassFitter` and `AliHFVnVsMassFitter` from `AliPhysics` to standalone classes for v2 D-meson analysis
> Extracted inv mass fitter from AliPhysics

- run3/flow/flow_analysis_utils.py
- run3/flow/get_vn_vs_mass.py
- run3/flow/invmassfitter/VnVsMassFitter.cxx
- run3/flow/invmassfitter/VnVsMassFitter.h
Hi, @Marcellocosti ! Thank you very much for extracting the inv mass fitter from AliPhysics, it will be more convenient to the fit.
At last time, I added the method of returning the function of Reflection and bkg + Reflection, the func into the simutaneous fit, and updated the `getD0ReflHistos`.
Taking this chance, I wish to add them to the new version.
Hi, @stefanopolitano, I've already tested locally, and it works. Please let me know if you have further suggestions or questions.
> Add the method of returning the reflection function

- run3/flow/run_full_flow_analysis.py
Hi, @stefanopolitano ! I have done this modification locally for a while, it would be better if we could copy the config name like this. If you permit it, we can use this one. But I am not sure you have to consider other cases so did this at the beginning.
> modified the config name for the copy

- ML/MLClassification.py
Update of the script `MLClassification.py` in order to perform optimization using the `Optuna` package and to save models in the `.onnx` file.
> ML in run3

- ML/MLApplication.py
- ML/MLClassification.py
Converted variable names in `MLApplication.py` and added configurable to store config files used for training and application in the output folder.
> Conversion to run3 for ML scripts

- ML/MLClassification.py
- run3/flow/project_thnsparse.py
With this PR, options to store the following information when performing ML models trainings are added:
- Text file saving the number of candidates taken into account in each pt bin for each class
- Plots of the hyperparameters' values as a function of the trial when hyperparameter optimization is performed
> Add info for ML
